# Generated by Django 5.1.6 on 2025-11-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, default=None, help_text='The date when the task is due.', null=True),
        ),
    ]
